### ISSUE TITLE
BadRequestError

### ISSUE THREAD

**Issue by BatunaAz** [sendbird/sendbird-chat-sample-flutter#19]
SDK version: sendbird_sdk: ^3.1.4

I received error: "BadRequestError": 
![Screen Shot 2021-10-02 at 18 11 47](https://user-images.githubusercontent.com/41317761/135711955-09fe2487-cb5a-4225-b5d4-68ef8330bf38.png)

i has updated sendbird_sdk: ^3.1.1 to sendbird_sdk: ^3.1.4 but i still receive same error. Please let me know what should i do.

**Comment by jalakoo** [comment]
@BatunaAz, are you still seeing that BadRequestError in version 3.1.7?
